version: 1.0.{build}

cache:
- PSO2H\packages -> **\PSO2H\packages.config

configuration:
- Release
- Debug

before_build:
- cmd: >-
    nuget restore PSO2H\PSO2H.sln

after_build:
- cmd: git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%/gitshort.txt
- cmd: set /P GITSHORT=<%TMP%/gitshort.txt
- set BUILD_ARCHIVE=%APPVEYOR_REPO_BRANCH%-%GITSHORT%-%CONFIGURATION%.7z
- cmd: 7z a %BUILD_ARCHIVE% PSO2H\bin\%CONFIGURATION% -xr!.gitignore
- appveyor PushArtifact %BUILD_ARCHIVE%

build:
  verbosity: minimal
